[package]
name = "records-service"
version = "0.1.0"
edition = "2024"

[dependencies]
# Shared migration framework
mongodb-migrator = { path = "../../shared/mongodb-migrator" }

# GraphQL & Web Framework
async-graphql = { version = "7.0.13", features = ["chrono", "tracing"] }
async-graphql-axum = "7.0.2"
axum = "0.8.4"
axum-macros = "0.5.0"
tower = "0.4"
tower-http = { version = "0.5.2", features = ["cors", "add-extension"] }

# Async Runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# MongoDB
mongodb = "2.8"
bson = { version = "2.10.0", features = ["chrono-0_4"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
anyhow = "1.0.86"
thiserror = "1.0"
async-trait = "0.1"
inventory = "0.3"

# Environment & Config
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI
clap = { version = "4.0", features = ["derive"] }
