[package]
name = "mongodb-migrator"
version = "0.1.0"
edition = "2021"
description = "A flexible, inventory-based MongoDB migration framework for Rust services"
authors = ["Your Team"]
license = "MIT"

[dependencies]
# Core async/database
mongodb = "2.8"
bson = { version = "2.10.0", features = ["chrono-0_4"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization & utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
anyhow = "1.0.86"
thiserror = "1.0"
async-trait = "0.1"
futures-util = "0.3.31"
# Auto-discovery
inventory = "0.3"
regex = "1.0"

# Logging
tracing = "0.1"

# CLI (optional)
clap = { version = "4.0", features = ["derive"], optional = true }

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"

[features]
default = ["cli"]
cli = ["clap"]  # CLI utilities for migration management
