import * as bcrypt from 'bcrypt';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateInitialAdminUser1756830683392 implements MigrationInterface {
  name = 'CreateInitialAdminUser1756830683392';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Normalize env vars
    const rawEmail = process.env.ADMIN_EMAIL || '';
    const rawPassword = process.env.ADMIN_PASSWORD || '';
    const adminEmail = rawEmail.trim();
    const adminPassword = rawPassword.trim();

    if (!adminEmail) {
      throw new Error('ADMIN_EMAIL environment variable is required for creating initial admin user');
    }
    if (!adminPassword) {
      throw new Error('ADMIN_PASSWORD environment variable is required for creating initial admin user');
    }

    // Check if admin user already exists
    const existingAdmin = await queryRunner.query(`SELECT id FROM "user" WHERE email = $1 LIMIT 1`, [adminEmail]);
    if (existingAdmin.length > 0) {
      console.log('Admin user already exists, skipping creation');
      return;
    }

    // Hash the password
    const saltRounds = 12;
    const hashedPassword = await bcrypt.hash(adminPassword, saltRounds);

    // Create admin user (id generated by DEFAULT uuid_generate_v4())
    await queryRunner.query(
      `INSERT INTO "user" (
                email,
                password,
                permissions,
                "isEmailVerified",
                "failedLoginAttempts",
                "createdAt",
                "updatedAt"
            ) VALUES (
                $1,
                $2,
                $3,
                true,
                0,
                NOW(),
                NOW()
            )
            ON CONFLICT (email) DO NOTHING`,
      [adminEmail, hashedPassword, 'admin,user']
    );

    console.log(`✅ Created initial admin user: ${adminEmail}`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const adminEmail = (process.env.ADMIN_EMAIL || '').trim();
    if (!adminEmail) {
      console.log('ADMIN_EMAIL not set, skipping admin user removal');
      return;
    }
    // Remove the admin user
    await queryRunner.query(`DELETE FROM "user" WHERE email = $1`, [adminEmail]);

    console.log(`🗑️  Removed admin user: ${adminEmail}`);
  }
}
